### ISSUE TITLE
Develop an App for quick segmentation of myelin and/or axons with manual selection

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#159] opened 2019-01-10 19:32 UTC
Typical scenario:
- Load image
- Run prediction
- Overlay prediction on image
- Zoom in particular location
- Edit myelin segmentation in one axon. Myelin should be a closed surface
- Fill axon segmentation (single click inside the axon)
- Do the same in X axons
- Save the segmentation as a single file

Idea to explore: Implement GUI in FSLeyes
- Add plugin to run ADS within FSLeyes
- Convert image into nifti

Inspiring projects:
- http://www.cs.toronto.edu/~amlan/demo/

**Comment by Stoyan-I-A** [comment] 2019-01-10 20:03
Thank you! As discussed, I will look into it this weekend. 
I am still a bit new to GitHub, can I mark this issue as "Assigned to me"?

**Comment by jcohenadad** [comment] 2019-01-10 21:05
> can I mark this issue as "Assigned to me"?

@Stoyan-I-A absolutely, i just added you in the team-- once you accept the invitation you should be able to assign yourself

**Comment by mathieuboudreau** [comment] 2019-01-10 22:43
Welcome @Stoyan-I-A ! Let me know if you have any questions getting set up. We're close to merging a new recommended installation guideline, but it's not the one you see if you click the doc badge on the repo yet. You can see them here: https://axondeepseg.readthedocs.io/en/update_doc/documentation.html#installation

**Comment by Stoyan-I-A** [comment] 2019-01-14 02:15
I installed the development version of AxonDeepSeg by following the instructions and it seems to be installed correctly. I was able to perform a segmentation using the axondeepseg command through the Anaconda command prompt. However, I'm confused on how to implement a script into the software. I was able to write a script that would print "Hello world" and execute it through the Anaconda Prompt, but if I try to import a package such as numpy, I get an error saying that the numpy module can't be found.

In the meantime, I installed the stable version on another python environment. I was able to reproduce the exemple in the "getting_started" Jupyter notebook. 
I also tried the GIMP software to see what the documentation currently suggests for manual segmentation.

Here are my thoughts on what the segmentation app would look like:
The app will be on an interface where the user will be able to look at a microscopy image as well as the masks corresponding to the axons and myelin. The user will be able to edit the masks using various segmentation tools.
These tools would include :
- A brush, similar to the GIMP software
- A tool to apply the axondeepseg script on a portion of the image
- A tool to draw a polygon on a region and add it to a mask
- A watershed segmentation grid, [similar to the tool in Slice-O-Matic](http://www.tomovision.com/products/subpages/images/sliceO_morpho.jpg)
- A local histogram threshold segmentation

More tools could be added if I have enough time.

**Comment by mathieuboudreau** [comment] 2019-01-14 15:04
@Stoyan-I-A Great to hear that the new installation steps worked for you!

>However, I'm confused on how to implement a script into the software. I was able to write a script that would print "Hello world" and execute it through the Anaconda Prompt, but if I try to import a package such as numpy, I get an error saying that the numpy module can't be found.

Could you clarify what you mean by *I'm confused on how to implement a script into the software.*? Are you trying to write a script in another software using AxonDeepSeg, or do you mean how to write a Python script with the AxonDeepSeg package? 

If it's the latter, then it's as simply as creating a new *.py Python file, and importing the necessary AxonDeepSeg module(s). One example of such a script is the file [AxonDeepSeg/integrity_test.py](https://github.com/neuropoly/axondeepseg/blob/master/AxonDeepSeg/integrity_test.py). There are several other similar ones in the [testing folder](https://github.com/neuropoly/axondeepseg/tree/master/test), for files intended to be used with the Py.Test testing package.

If however you mean that you are trying to write AxonDeepSeg scripts in another software, I've never done this, but I think that for the software to be able to see AxonDeepSeg in its path, you may need to open it in the command line (after activating your Virtual Environment) instead of opening it on your OS GUI (e.g. double clicking the icon). But I've not tested this – this is just what I've had to do for similar projects with MATLAB in the past.

**Closed** 2019-10-14 17:34 UTC
