### ISSUE TITLE
Installation: Update doc

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#142] opened 2018-11-06 22:55 UTC
- currently the [doc](https://axondeepseg.readthedocs.io/en/stable/documentation.html#axondeepseg) suggests to install v1.9.0, which based on the recent PR #140 should be v1.3.0
- we should provide an intuitive step-by-step installation with miniconda to make sure people install proper version of conda, pip, venv, etc. to avoid problems like this one #143

**Comment by mathieuboudreau** [comment] 2018-11-06 23:37
We should also add installation instructions if they intend to use their GPU (tensorflow needs to be uninstalled, and tensorflow-gpu==1.3.0 needs to be installed afterwards).

**Comment by mathieuboudreau** [comment] 2018-11-09 02:14
@jcohenadad Have you had any success installing/running ADS within a miniconda venv on Rosenberg? I tried  doing so again, but still keep getting errors that are hinting that my miniconda venv might not be "closed". Here are the steps I followed:

* `wget https://repo.continuum.io/miniconda/Miniconda3-3.7.0-Linux-x86_64.sh -O ~/miniconda.sh`
* `bash ~/miniconda.sh -b -p $HOME/miniconda`
* `echo 'export PATH="$HOME/miniconda/bin:$PATH"' >> ~/.bashrc`
* `source ~./bashrc`
* `conda create -n ads_venv python=3.6`
* `source activate ads_venv`
* `git clone https://github.com/neuropoly/axondeepseg.git`
* `cd axondeepseg`
* `~/miniconda/envs/ads_venv/bin/pip install -e .` -> Had to do this on my first try, as `which pip` indicated to me that my shell was seeing the user's pip, not the venv. When I later relogged in and activated my venv again, `pip` pointed to the right one.

At this point, I've had several different sorts of errors when trying to run the testing suite.

e.g. 

<details>

```

(ads_venv)[mabou_local@rosenberg axondeepseg]$ py.test --cov AxonDeepSeg/ --cov-report term-missing
========================================================================================= test session starts =========================================================================================
platform linux -- Python 3.6.5, pytest-3.5.0, py-1.7.0, pluggy-0.6.0
rootdir: /home/mabou_local/neuropoly/github/miniconda_test/axondeepseg, inifile:
plugins: cov-2.5.1
collected 38 items / 8 errors                                                                                                                                                                         

=============================================================================================== ERRORS ================================================================================================
___________________________________________________________________________ ERROR collecting AxonDeepSeg/integrity_test.py ____________________________________________________________________________
AxonDeepSeg/integrity_test.py:11: in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
AxonDeepSeg/apply_model.py:5: in <module>
    from AxonDeepSeg.network_construction import *
AxonDeepSeg/network_construction.py:21: in <module>
    w_initializer=tf.contrib.layers.xavier_initializer_conv2d(),
E   AttributeError: module 'tensorflow' has no attribute 'contrib'
____________________________________________________________________________ ERROR collecting test/test_integrity_test.py _____________________________________________________________________________
test/test_integrity_test.py:4: in <module>
    from AxonDeepSeg.integrity_test import integrity_test
<frozen importlib._bootstrap>:971: in _find_and_load
    ???
<frozen importlib._bootstrap>:955: in _find_and_load_unlocked
    ???
<frozen importlib._bootstrap>:656: in _load_unlocked
    ???
<frozen importlib._bootstrap>:626: in _load_backward_compatible
    ???
../../../../.local/lib/python3.6/site-packages/_pytest/assertion/rewrite.py:213: in load_module
    py.builtin.exec_(co, mod.__dict__)
AxonDeepSeg/integrity_test.py:11: in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
AxonDeepSeg/apply_model.py:5: in <module>
    from AxonDeepSeg.network_construction import *
AxonDeepSeg/network_construction.py:21: in <module>
    w_initializer=tf.contrib.layers.xavier_initializer_conv2d(),
E   AttributeError: module 'tensorflow' has no attribute 'contrib'
________________________________________________________________________________ ERROR collecting test/test_segment.py ________________________________________________________________________________
test/test_segment.py:5: in <module>
    from AxonDeepSeg.segment import *
AxonDeepSeg/segment.py:11: in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
AxonDeepSeg/apply_model.py:5: in <module>
    from AxonDeepSeg.network_construction import *
AxonDeepSeg/network_construction.py:21: in <module>
    w_initializer=tf.contrib.layers.xavier_initializer_conv2d(),
E   AttributeError: module 'tensorflow' has no attribute 'contrib'
_____________________________________________________________________________ ERROR collecting test/test_train_network.py _____________________________________________________________________________
test/test_train_network.py:10: in <module>
    from AxonDeepSeg.train_network import train_model
AxonDeepSeg/train_network.py:9: in <module>
    from AxonDeepSeg.network_construction import *
AxonDeepSeg/network_construction.py:21: in <module>
    w_initializer=tf.contrib.layers.xavier_initializer_conv2d(),
E   AttributeError: module 'tensorflow' has no attribute 'contrib'
__________________________________________________________________ ERROR collecting test/morphometrics/test_compute_morphometrics.py __________________________________________________________________
test/morphometrics/test_compute_morphometrics.py:11: in <module>
    from AxonDeepSeg.morphometrics.compute_morphometrics import *
AxonDeepSeg/morphometrics/compute_morphometrics.py:18: in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
AxonDeepSeg/apply_model.py:5: in <module>
    from AxonDeepSeg.network_construction import *
AxonDeepSeg/network_construction.py:21: in <module>
    w_initializer=tf.contrib.layers.xavier_initializer_conv2d(),
E   AttributeError: module 'tensorflow' has no attribute 'contrib'
____________________________________________________________ ERROR collecting test/morphometrics/test_launch_morphometrics_computation.py _____________________________________________________________
test/morphometrics/test_launch_morphometrics_computation.py:8: in <module>
    from AxonDeepSeg.morphometrics.launch_morphometrics_computation import *
AxonDeepSeg/morphometrics/launch_morphometrics_computation.py:13: in <module>
    from AxonDeepSeg.morphometrics.compute_morphometrics import *
AxonDeepSeg/morphometrics/compute_morphometrics.py:18: in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
AxonDeepSeg/apply_model.py:5: in <module>
    from AxonDeepSeg.network_construction import *
AxonDeepSeg/network_construction.py:21: in <module>
    w_initializer=tf.contrib.layers.xavier_initializer_conv2d(),
E   AttributeError: module 'tensorflow' has no attribute 'contrib'
_______________________________________________________________________ ERROR collecting test/testing/test_noise_simulation.py ________________________________________________________________________
test/testing/test_noise_simulation.py:8: in <module>
    from AxonDeepSeg.testing.noise_simulation import *
AxonDeepSeg/testing/noise_simulation.py:12: in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
AxonDeepSeg/apply_model.py:5: in <module>
    from AxonDeepSeg.network_construction import *
AxonDeepSeg/network_construction.py:21: in <module>
    w_initializer=tf.contrib.layers.xavier_initializer_conv2d(),
E   AttributeError: module 'tensorflow' has no attribute 'contrib'
_____________________________________________________________________ ERROR collecting test/testing/test_statistics_generation.py _____________________________________________________________________
test/testing/test_statistics_generation.py:8: in <module>
    from AxonDeepSeg.testing.statistics_generation import *
AxonDeepSeg/testing/statistics_generation.py:7: in <module>
    from AxonDeepSeg.apply_model import axon_segmentation
AxonDeepSeg/apply_model.py:5: in <module>
    from AxonDeepSeg.network_construction import *
AxonDeepSeg/network_construction.py:21: in <module>
    w_initializer=tf.contrib.layers.xavier_initializer_conv2d(),
E   AttributeError: module 'tensorflow' has no attribute 'contrib'

----------- coverage: platform linux, python 3.6.5-final-0 -----------
Name                                                            Stmts   Miss  Cover   Missing
---------------------------------------------------------------------------------------------
AxonDeepSeg/__init__.py                                             1      0   100%
AxonDeepSeg/ads_utils.py                                           71     45    37%   14-57, 65-91, 110, 126, 142-154, 162-167
AxonDeepSeg/apply_model.py                                        158    155     2%   6-485
AxonDeepSeg/config_tools.py                                       107     85    21%   28-32, 103-109, 119-127, 132-137, 140-145, 153-181, 188-229, 235-265, 269-276
AxonDeepSeg/data_management/__init__.py                             0      0   100%
AxonDeepSeg/data_management/data_augmentation.py                  141    125    11%   27-49, 62-114, 127-145, 157-191, 203-208, 219-244, 257-270
AxonDeepSeg/data_management/dataset_building.py                   115    103    10%   27-64, 78-198, 209, 221-235
AxonDeepSeg/data_management/input_data.py                         191    164    14%   16-46, 56-61, 70-74, 83-94, 103-122, 145-175, 178, 187-202, 211-241, 254-291, 300, 309-331, 346-363, 373-392, 402-427
AxonDeepSeg/data_management/patch_extraction.py                    40     36    10%   12-55
AxonDeepSeg/integrity_test.py                                      36     31    14%   12-66
AxonDeepSeg/mapping_results.py                                     29     29     0%   4-60
AxonDeepSeg/models/__init__.py                                      0      0   100%
AxonDeepSeg/morphometrics/__init__.py                               0      0   100%
AxonDeepSeg/morphometrics/compute_morphometrics.py                 98     84    14%   13-14, 19-197
AxonDeepSeg/morphometrics/launch_morphometrics_computation.py      26     18    31%   9-10, 14-53
AxonDeepSeg/network_construction.py                                78     67    14%   29-237
AxonDeepSeg/patch_management_tools.py                              63     56    11%   13-16, 27-30, 44-72, 86-139
AxonDeepSeg/segment.py                                            149    147     1%   12-404
AxonDeepSeg/testing/__init__.py                                     0      0   100%
AxonDeepSeg/testing/launch_performance_metrics.py                  26     13    50%   23-48
AxonDeepSeg/testing/noise_simulation.py                            29     20    31%   13-75
AxonDeepSeg/testing/segmentation_scoring.py                       150    121    19%   12-14, 32-98, 112-141, 149-155, 161-162, 167-173, 178-184, 189-195, 200, 205, 210-216, 221, 226-235, 240-249, 254-267, 272-281
AxonDeepSeg/testing/statistics_generation.py                      209    204     2%   8-466
AxonDeepSeg/train_network.py                                      297    290     2%   10-648
AxonDeepSeg/train_network_tools.py                                 49     49     0%   4-123
AxonDeepSeg/trainingforhelios.py                                   26     26     0%   5-49
AxonDeepSeg/visualization/__init__.py                               0      0   100%
AxonDeepSeg/visualization/generate_axons_from_myelin.py            17     10    41%   22-46
AxonDeepSeg/visualization/get_masks.py                             28     19    32%   11-32, 43-54
AxonDeepSeg/visualization/merge_masks.py                           11      6    45%   8-19
AxonDeepSeg/visualization/visualize.py                            120    100    17%   7-9, 31-52, 65-151, 162-176, 187-188, 192-200
---------------------------------------------------------------------------------------------
TOTAL                                                            2265   2003    12%

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 8 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
======================================================================================= 8 error in 3.08 seconds =======================================================================================


```

</details></p>

and after I followed some instruction online for force reinstalling tensorflow, I now got this:

<details>

```

(ads_venv)[mabou_local@rosenberg axondeepseg]$ py.test --cov AxonDeepSeg/ --cov-report term-missing
Traceback (most recent call last):
  File "/home/mabou_local/.local/bin/py.test", line 7, in <module>
    from pytest import main
  File "/home/mabou_local/.local/lib/python3.6/site-packages/pytest.py", line 9, in <module>
    from _pytest.config import (
  File "/home/mabou_local/.local/lib/python3.6/site-packages/_pytest/config.py", line 9, in <module>
    import six
ModuleNotFoundError: No module named 'six'

```

</details></p>

As you can see in the next `details` section, when running pip install, it shows that the majority of my packages are already installed in my users default folder, not in my venv folder.

<details>

```

(ads_venv)[mabou_local@rosenberg axondeepseg]$ pip install -e .
Obtaining file:///home/mabou_local/neuropoly/github/miniconda_test/axondeepseg
Requirement already satisfied: numpy==1.14.5 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: scipy==1.1.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: scikit-learn==0.19.2 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: scikit-image==0.13.1 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: tabulate==0.8.2 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: pandas==0.23.3 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: matplotlib==2.2.2 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: tensorflow==1.3.0 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: mpld3==0.3 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: tqdm==4.24.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: pillow==5.2.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: imageio==2.3.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: pytest==3.5.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: pytest-cov==2.5.1 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: prettytable==0.7.2 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: raven==6.8.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from AxonDeepSeg==2.2.dev0)
Requirement already satisfied: networkx>=1.8 in /home/mabou_local/.local/lib/python3.6/site-packages (from scikit-image==0.13.1->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: six>=1.7.3 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from scikit-image==0.13.1->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: PyWavelets>=0.4.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from scikit-image==0.13.1->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: python-dateutil>=2.5.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from pandas==0.23.3->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: pytz>=2011k in /home/mabou_local/.local/lib/python3.6/site-packages (from pandas==0.23.3->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: cycler>=0.10 in /home/mabou_local/.local/lib/python3.6/site-packages (from matplotlib==2.2.2->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: pyparsing!=2.0.4,!=2.1.2,!=2.1.6,>=2.0.1 in /home/mabou_local/.local/lib/python3.6/site-packages (from matplotlib==2.2.2->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: kiwisolver>=1.0.1 in /home/mabou_local/.local/lib/python3.6/site-packages (from matplotlib==2.2.2->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: protobuf>=3.3.0 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from tensorflow==1.3.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: tensorflow-tensorboard<0.2.0,>=0.1.0 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from tensorflow==1.3.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: wheel>=0.26 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from tensorflow==1.3.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: attrs>=17.4.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from pytest==3.5.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: more-itertools>=4.0.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from pytest==3.5.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: setuptools in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from pytest==3.5.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: pluggy<0.7,>=0.5 in /home/mabou_local/.local/lib/python3.6/site-packages (from pytest==3.5.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: py>=1.5.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from pytest==3.5.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: coverage>=3.7.1 in /home/mabou_local/.local/lib/python3.6/site-packages (from pytest-cov==2.5.1->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: decorator>=4.3.0 in /home/mabou_local/.local/lib/python3.6/site-packages (from networkx>=1.8->scikit-image==0.13.1->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: markdown>=2.6.8 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow==1.3.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: html5lib==0.9999999 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow==1.3.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: bleach==1.5.0 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow==1.3.0->AxonDeepSeg==2.2.dev0)
Requirement already satisfied: werkzeug>=0.11.10 in /home/mabou_local/miniconda/envs/ads_venv/lib/python3.6/site-packages (from tensorflow-tensorboard<0.2.0,>=0.1.0->tensorflow==1.3.0->AxonDeepSeg==2.2.dev0)
Installing collected packages: AxonDeepSeg
  Found existing installation: AxonDeepSeg 2.2.dev0
    Uninstalling AxonDeepSeg-2.2.dev0:
      Successfully uninstalled AxonDeepSeg-2.2.dev0
  Running setup.py develop for AxonDeepSeg
Successfully installed AxonDeepSeg
You are using pip version 9.0.1, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

```

</details></p>

The only way I've had success (on Rosenberg) so far with is by creating a venv using the command `python3.6 -m virtualenv venv_ads`, which I know is less ideal than using conda or Anadonda, particularly for general instructions in the documentation.

**Comment by jcohenadad** [comment] 2018-11-09 02:30
i managed to get ads running with miniconda 3.6., however i did it on bireli (not rosenberg), because all GPU are jammed ;-)

so, i am wondering if there is something that has to do with rosenberg /usr/'s installations? the fact that pip pointed to the wrong one (before you rebooted) is highly suspicious (and maybe related to all the following issues?). 

Maybe you can try to reproduce the exact same procedure on bireli (or another station) to see what happens?

**Comment by mathieuboudreau** [comment] 2018-11-09 03:33
Good insight - after digging some more I decided to delete `/home/mabou_local/.local/lib/python3.6/site-packages` because it had a lot of conflicting packages, and then pip install & py.test worked fine. Not sure why this folder was being accessed/seen when running within a conda venv, I'm wondering if I caused this issue with some of my previous tests/debuggings.

I'll try the miniconda steps from scratch on bireli (@alexfoias can you make me an account?), and then take a look at my command history to see if I can reproduce this issue, and how it can be avoided.

**Comment by alexfoias** [comment] 2018-11-09 15:21
@mathieuboudreau You can use your polygrames account to connect to bireli. We are currently facing some network problems and the authentification might not work. I contacted the network admin and should be fixed soon. I will slack you once is fixed. Sorry for the delay.

**Closed** 2019-01-11 20:07 UTC
