### ISSUE TITLE
Error with segment_folder function in segment.py

### ISSUE THREAD

**Issue by mariehbourget** [neuropoly/axondeepseg#318] opened 2020-06-25 20:30 UTC
I found two problems while trying to segment multiple images in the same folder.

1) In the documentation, there is a space in the filename that shouldn't be there (`image 1_sem/`) [here](fileName). 

2) Even though the test for segment_folder is passing, the command in the documentation doesn't work. There is a problem with the path folder being duplicated, so the images are not found.

I'm going to open a PR to fix it and see what happen with the test after.

**Comment by mathieuboudreau** [comment] 2020-06-25 20:36
Do you understand why the test is passing but the command is not?

**Comment by mariehbourget** [comment] 2020-06-25 20:41
I found the problem in segment_folders [here](https://github.com/neuropoly/axondeepseg/blob/0ed8b61b48ac55872fadc31f0a5b32436d1771ce/AxonDeepSeg/segment.py#L126), img_files is a list of path (not a list of filename).
So [here](https://github.com/neuropoly/axondeepseg/blob/0ed8b61b48ac55872fadc31f0a5b32436d1771ce/AxonDeepSeg/segment.py#L133), the path is duplicated (and everywhere with `path_testing_images_folder / file_` string.
I don't know why it doesn't raise problem in the tests

**Comment by mathieuboudreau** [comment] 2020-06-25 20:43
Instead of fixing the code and/or test right away, let's write a new test that will catch this bug, and then resolve it in the code.

**Comment by mariehbourget** [comment] 2020-06-25 21:52
Yes, good point. However, I can't find the difference between the tests and the command. From my understanding, the tests should fail as they are written now. Both are calling the segment_folder function with the filepath in argument.
If I correct the code for the command, the tests are still passing, but it means that they don't test what we want right now (which is not really better).  I'll keep looking.

**Comment by mathieuboudreau** [comment] 2020-06-25 21:58
What are the steps to follow to reproduce your error?

**Comment by mariehbourget** [comment] 2020-06-25 22:06
I followed the steps in RTD to segment using the CLI. It works with a single file but not with a folder [here](https://axondeepseg.readthedocs.io/en/latest/documentation.html#segment-multiple-images-of-the-same-resolution). As I wrote previously, there is a space in the filename that should be remove before running the command. I also put `-v 1` to see the name of the filename being segmented.

**Comment by mathieuboudreau** [comment] 2020-06-25 23:28
The error is happening when we only provide the relative path to the segment function. Providing the full path resolves the issue. e.g.,

`axondeepseg -t SEM -i "$(pwd)/test/__test_files__/__test_segment_files__/" -s 0.37`

Not sure why yet, tbd.

**Comment by mariehbourget** [comment] 2020-06-25 23:41
Thanks Mathieu for your help! I found the same thing at the same time on my side. For now, I will update the doc with the full path when dealing with folder.

**Comment by mathieuboudreau** [comment] 2020-06-26 00:14
@mariehbourget I found a solution - am pushing to PR soon

**Comment by mathieuboudreau** [comment] 2020-06-26 00:44
Resolving this issue introduced another bug - however that bug was due to lazy coding on my part a few months ago. I'll resolve it, it's just going to take me a little while long.

**Closed** 2020-06-26 06:26 UTC
