### ISSUE TITLE
Binder badge notebook:  ./postBuild: pip2: not found

### ISSUE THREAD

**Issue by mathieuboudreau** [neuropoly/axondeepseg#94] opened 2018-05-24 15:08 UTC
I tried running the Jupyter notebook available through clicking the badge on the README yesterday, and encountered this error:

`./postBuild: 3: ./postBuild: pip2: not found`

I know sometimes there are temporary issue with Binder, but I tried again today and couldn't access it (same error).

**Comment by alzaia** [comment] 2018-05-24 20:35
The postBuild script is basically the commands that we launch in order to install the package:
```
pip install wheel
python setup.py bdist_wheel --universal
pip2 install dist/AxonDeepSeg-0.3-py2.py3-none-any.whl
```
The issue is that the name of the wheel is hardcoded here (i.e. ```AxonDeepSeg-0.3-py2.py3-none-any.whl```), but it should depend on the current version of ADS (now it is 0.4) so it does not find the correct wheel. I will resolve this. Thanks for pointing it out!

**Comment by mathieuboudreau** [comment] 2018-05-24 20:37
Ah ha – thanks for explaining! No problem!

**Comment by alzaia** [comment] 2018-05-28 17:04
Fixed in PR #95

**Closed by alzaia** 2018-05-28 17:04 UTC
