### ISSUE TITLE
Check for solutions for the patch edges problem 

### ISSUE THREAD

**Issue by alzaia** [neuropoly/axondeepseg#17] opened 2017-06-02 20:26 UTC
Suggestions:

- use overlapping sliding window technique for the patch generation
- no need to apply it on small patches during testing time
- use different patch size for prediction and then combine overall results
- in input, enlarge the image (or patch) with mirroring at the edges (just 1 or 2 pixels padding)

**Comment by jcohenadad** [comment] 2017-12-09 14:25
never close an issue without referencing to the commit that fixes the issue.

**Comment by jcohenadad** [comment] 2018-03-30 01:08
duplicate of https://github.com/neuropoly/axondeepseg/issues/74

**Closed** 2018-08-23 19:02 UTC
Labels: priority:MEDIUM
