### ISSUE TITLE
Patchy appearance of segmentation results

### ISSUE THREAD

**Issue by jcohenadad** [neuropoly/axondeepseg#74] opened 2018-03-28 02:17 UTC
![anim](https://user-images.githubusercontent.com/2482071/38004962-9c73a14a-3279-11e8-9f70-e7edffbf5784.gif)

**Comment by jcohenadad** [comment] 2018-07-04 16:13
sorry i did not indicate the original data that was used. so, let's try to reproduce the bug on a dataset. Maybe try this: https://osf.io/jbh32/, or other images from the same repository.

**Comment by jcohenadad** [comment] 2018-07-04 16:18
to reproduce, download this gif from github and only keep the image part (remove the seg).

this bug is likely related to the presence of the white/gray border in the image. If that's the case, then we can drop the priority, and maybe consider adding a check in the future (e.g., look for regions with 0 STD in a given neighbourhood).

**Comment by jcohenadad** [comment] 2018-08-16 16:52
info from @oumayb: she tested on data without border and also obtained similar artifact.

**Comment by oumayb** [comment] 2018-08-16 18:39
@jcohenadad do you have the pixel size for this image please?

**Comment by jcohenadad** [comment] 2018-08-16 20:00
@oumayb i think these are the data from Shawn Mikula

**Comment by jcohenadad** [comment] 2018-08-23 19:03
@oumayb can you check with varying the value of the flag `-o`, see if it has an impact, and if does it means that we need to look into how the overlap is managed inside the code.

**Comment by vs74** [comment] 2019-07-02 18:54
@jcohenadad. I was trying to reproduce the error due to patchy appearance. Do you remember where the image is taken from ? I checked in Mikula dataset but none of the images resembled to this one.

**Comment by jcohenadad** [comment] 2019-07-02 19:07
@vs74 i think it's from OSF: https://osf.io/yp4qg/, NYU or Vanderbilt site. If you cannot find it, just download this image from this thread on github ;-)

**Comment by vs74** [comment] 2019-07-03 19:07
![34v6sy](https://user-images.githubusercontent.com/31419210/60617430-b85e6400-9da1-11e9-8c50-359b076242ba.gif)
I tried to reproduce the above patchy edge by downloading gif from GitHub, however I didn't get the patchy appearance of segmentation results.Though the results were quite good. The following syntax used was used to produce the above images:
`axondeepseg -t TEM -i /Users/vasha_admin/PycharmProjects/axondeepseg/AxonDeepSeg/data_test/image.png -s 0.01 -v 3`
1. Branch -` master`( commit  32c8099)
2. model - `TEM`
3. resolution - `0.01`
4. pixel_size_in_micrometer.txt - `0.07`.

Right now it's seem fine. There are no patchy appearance. Since I was unable to reproduce the results pointed out by @jcohenadad  and ADS segmentation is also working fine, I am closing this issue. However if in future we see patchy appearance, we can re-open this issue.

**Closed by vs74** 2019-07-03 19:07 UTC
Labels: priority:LOW

**Comment by mathieuboudreau** [comment] 2019-07-08 13:47
Curious to know what commit number resolved this, I might jump a few spots in the past few months to see what fixed this.

**Comment by jcohenadad** [comment] 2019-07-08 16:29
> Curious to know what commit number resolved this, I might jump a few spots in the past few months to see what fixed this.

the debugging should also include the way @vs74 re-created the image from the downloaded gif as i can see many ways via which the image i used and the image @vs74 used were different (format, quantization, etc.) ;-)
